### ISSUE TITLE
is there any plan about develop the ios or winphone version ?

### ISSUE THREAD

**Issue by bau720123** [pwlin/cordova-plugin-pdialog#1]
hi @pwlin 
awesome plugin and work perfect
well..
just want to ask...
is there any plan about develop the ios or winphone version ?

**Comment by pwlin** [comment]
Hi @bau720123 
Glad you like this plugin too! At this moment I have no plan for developing an iOS or Windows version. But in the future I will support those devices too. I will let you know when I have some code ready. Thanks for your support.

**Comment by bau720123** [comment]
hi @pwlin 
thanks you too
again that I must say
awesome plugin !!!

**Comment by sam2x** [comment]
Hey, any news about this ? would love to see the ios support ? or any ideas if there is any ios-like plugin ?
