### ISSUE TITLE
[just a recommand] move to the npm

### ISSUE THREAD

**Issue by bau720123** [pwlin/cordova-plugin-pdialog#4]
hi @pwlin 

according to these
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html
so...just want to inform you that your plugin should be move to npm in the future...

**Comment by pwlin** [comment]
Hi @bau720123 
Nice to hear from you again!
I'll be moving this plugin to NPM this weekend, I've moved my other plugin (file-opener2) to NPM a while back too. Thank you very much for the reminder and helpful links. I'll let you know when it's done.

**Comment by bau720123** [comment]
thanks @pwlin 
you are awesome!!!

**Comment by pwlin** [comment]
Hi @bau720123 
I published a new version (`2.0.0`) to NPM.
Please install with:

`cordova plugin add cordova-plugin-pdialog`

Let me know if there are problems.

**Comment by bau720123** [comment]
no problem at all
thanks @pwlin
