### ISSUE TITLE
just a name feedback

### ISSUE THREAD

**Issue by bau720123** [pwlin/cordova-plugin-pdialog#5]
hi @pwlin 
your plugin is "cordova-plugin-pdialog"
https://www.npmjs.com/package/cordova-plugin-pdialog

but your plugin.xml
https://github.com/pwlin/cordova-plugin-pdialog/blob/master/plugin.xml
clobbers's name become "cordova.plugins.pDialog"
More than a "s"
it won't cause any problem
but more Consistency more better

cordova_plugins.js

```
{
        "file": "plugins/cordova-plugins-pdialog/www/plugins.PDialog.js",
        "id": "cordova-plugins-pdialog.PDialog",
        "clobbers": [
            "cordova.plugins.pDialog"
        ]
    },
```

**Comment by pwlin** [comment]
Hi @bau720123 
I changed the clobber to `cordova.plugin.pDialog` and pushed a new version (`2.0.1`) to NPM. Please remove the older version and test with the new one.

**Comment by bau720123** [comment]
thanks @pwlin
